namespace TextileEditor.Web.Localization;

public class SharedResource
{
    public const string Color = nameof(Color);
    public const string Mode = nameof(Mode);
    public const string Theme = nameof(Theme);
    public const string Options = nameof(Options);
    public const string File = nameof(File);
    public const string New = nameof(New);
    public const string Open = nameof(Open);
    public const string Save = nameof(Save);
    public const string SaveAs = nameof(SaveAs);
    public const string Language = nameof(Language);
    public const string FileName = nameof(FileName);
    public const string SaveAsType = nameof(SaveAsType);
    public const string Download = nameof(Download);
    public const string Upload = nameof(Upload);
    public const string Done = nameof(Done);
    public const string View = nameof(View);
    public const string Edit = nameof(Edit);
    public const string CreateNew = nameof(CreateNew);
    public const string Create = nameof(Create);
    public const string Delete = nameof(Delete);
    public const string Rename = nameof(Rename);
    public const string Cancel = nameof(Cancel);
    public const string TextileExplorer = nameof(TextileExplorer);
    public const string Textile = nameof(Textile);
    public const string Heddle = nameof(Heddle);
    public const string Pedal = nameof(Pedal);
    public const string Tieup = nameof(Tieup);
    public const string HeddleColor = nameof(HeddleColor);
    public const string PedalColor = nameof(PedalColor);
    public const string RenderingTextile = nameof(RenderingTextile);
    public const string TotalStep = nameof(TotalStep);
    public const string Config = nameof(Config);
    public const string NotSelectedTextile = nameof(NotSelectedTextile);
    public const string Preview = nameof(Preview);
    public const string GenerateDownloadLink = nameof(GenerateDownloadLink);
    public const string ClickToInvert = nameof(ClickToInvert);
    public const string SelectCopyRange = nameof(SelectCopyRange);
    public const string Paste = nameof(Paste);
    public const string Copy = nameof(Copy);
    public const string ClearTextile = nameof(ClearTextile);
    public const string ClickToSetColor = nameof(ClickToSetColor);
    public const string Redo = nameof(Redo);
    public const string Undo = nameof(Undo);
    public const string BuildSettingsToTextile = nameof(BuildSettingsToTextile);
    public const string BuildTextileToSettings = nameof(BuildTextileToSettings);
    public const string SaveLocalStorage = nameof(SaveLocalStorage);
    public const string SelectAHorizontalRepeat = nameof(SelectAHorizontalRepeat);
    public const string SelectAVerticalRepeat = nameof(SelectAVerticalRepeat);
    public const string SelectAPixelWidth = nameof(SelectAPixelWidth);
    public const string SelectAPixelHeight = nameof(SelectAPixelHeight);
    public const string Home = nameof(Home);
}
